apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
        - name: node-container
          image: mohasan/url-shortener-app
          ports:
            - containerPort: 3030
          envFrom:
            - configMapRef:
                name: app-config
