apiVersion: v1
kind: Service
metadata:
  name: node-service
spec:
  selector:
    app: node-app
  ports:
    - name: node-app
      protocol: TCP
      
      port: 3030
      targetPort: 3030
  type: ClusterIP
